
version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
     MYSQL_ROOT_PASSWORD: dev_pass_123   # ✅ no equal sign (=), no quotes
     MYSQL_DATABASE: shopping_db
     MYSQL_USER: dev_user                # ✅ you should add this
     MYSQL_PASSWORD: dev_pass_123        # ✅ you should add this
    volumes:
      - mysql_data:/var/lib/mysql  

volumes:
  mysql_data: